---
title: "To do list for this paper"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Don't spend any time placing the figures!!!!! Place figure just in front of the paragraph of text describing it. 

## Broadly

- [ ] Write an abstract - Gelman method/sanity check. First sentence of every paragraph of the intro & the very last sentence of intro. 
- [ ] Submit to journal
- [X] Spacing around figures WAY to large above/below captions - change fig.height for coord_fixed figures 
- [X] Make axes labels and text larger in figures
- [X] Make labels of points larger
- [ ] Reverse order of x-y axes on adjmat vizs 

## Introduction

- [ ] Proof read

## Section 2

- [ ] Proof read
- [X] Make sure I've defined ego/alter nodes
- [ ] Need to talk about the CTMC, rest of the SAOM model definition after the objective function discussion. 

## Section 3 

- [ ] Proof read
- [ ] Finish section 3.1 (elaborate on probability)

## Section 4 

- [ ] Add histogram of number of tie changes from $t_1$ to $t_2$ in simulations 
- [ ] Add another example of a data set for M-in-DS (Sect 4.1) (Congress)
- [ ] Make gif available online
- [ ] Insert link to full gif in paper
- [X] Figure 6: reverse order of adjacency matrix y-axis
- [X] Figure 5: get rid of Vs on node labels, make font bigger
- [X] Figure 7 not showing up??
- [X] Fix error on p. 21 (probably related to above)
- [X] Heatmap p 23 missing caption
- [X] Describe Figure 8 more. What is going on??
- [ ] Add geomnet example in 4.2
- [X] p. 26-28 figure refs & code is broken
- [X] Get rid of repeated plot p 29
- [X] p. 34 code is broken
- [ ] General proof reading

## Discussion

- [ ] Write up conclusions
- [ ] Discuss future work
