---
title: "Visualizing the CTMC and SAOM fitting process"
output: github_document
---

This outline exists to help me get my thoughts straight with respect to my process of visualizing the SAOM fitting process and the underlying CTMC for network change. Why am I doing this? What am I going to do? What have I already done? What do I want to accomplish? 

# Outline

1. Visualize the CTMC
    a. Why? - to better understand the model. to see what's going on underneath. to see how the objective function affects tie changes.
    b. How? - write a function to simulate from time 1 to time 2 given parameter values that stores the network at each step, the time between each step, and any covariate values. visualize the one-tie-at-a-time changes in a movie, facets, any other way. use color or shape changes to see how the covariate levels affect the changes.
    c. What? - this will become part of the "removing the blindfold" chapter. introduction and first sections
2. Visualize the fitting process
    a. Why? - to better understand the updating process. to see what's influencing the parameter estimates most. 
    b. How? - write a function that mimics the `RSiena` fitting process for Method of Moments OR figure out how to extract the parameter updates from the `sienafit` object. visualize the chains of parameter changes. look at how different parameter values for starting values affect the estimations.
    c. What? - this will become part of the "removing the blindfold" chapter. Maybe model-in-data-space section. 
    
# Ideas from "Visualizing Statistical Models: Removing the Blindfold"

1. Introduction
    a. Talk about the toolbox of visualizations. We must answer the question, "What is in the network visualization toolbox?" and use those tools and more moving forward.
2. Background 
    a. Model family - the SAOM is the model family
    b. Model form - which $\beta$ effects get included
    c. Fitted model - estimates of rate parameters and $\beta$s resulting from `RSiena` fit
    d. Question: Can we find a direct interpretation of the SAOM $\beta$ parameters? The $\beta$s are in the model space. How can we take them from the model space to the data space? 
    e. Question: How can we visualize these networks interactively?? 
3. Display the Model in Data-Space
    a. What does visualizing the model in the data space mean for SAOMs? 
        i. Idea: take the `sims` output object from the SAOM model fit. Create adjaceny matrices from them, tile them in `geom_tile`, shading by frequency of specific ties in simulations, then overlay the squares that are in the data that was being simulated. 
        ii. Idea: focus on the probabilities of individual tie changes. How do close probabilities affect overall model behavior?? 
4. Collections are more informative than singletons
    a. We've already done some of this - densities of fitted estimates from `RSiena`. 
    b. Look at distributions of fitted network statistics (corresponding to stats in model form) by the fitted parameter values. I also think we've already done some of this. 
    c. Other ideas????
5. Do not just look at the final result; explore how the algorithm works
    a. Idea: We've already discussed visualizing the microsteps from current time to the next time point.
    b. Idea: Look at the chains for updating the parameter estimates -- use multiple starting values. 
